name: petpal
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  url_launcher: ^6.1.7
  cupertino_icons: ^1.0.8
  firebase_core: ^3.10.0
  cloud_firestore: ^5.6.1
  firebase_auth: ^5.4.0
  google_sign_in: ^6.2.2
  firebase_storage: ^12.4.0
  image_picker: ^0.8.7
  firebase_app_check: ^0.3.2
  timeago: ^3.7.0
  google_fonts: ^6.2.1
  intl: ^0.19.0  # Downgraded to resolve conflict
  flutter_staggered_grid_view: ^0.7.0
  cached_network_image: ^3.3.0
  flutter_riverpod: ^2.6.1
  flutter_svg: ^2.0.17



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - images/
    - images/login.png
    - images/banner.png
    - images/catpaw.png
    - images/clinic.jpg
    - images/1.jpg
    - images/2.jpg
    - images/3.jpg
    - images/logo.png
    - images/logo11.png
    - images/emon.jpg
    - images/jamal.jpg
    - images/abir.jpg
    - images/tonmoy.jpg